version: '3.8'

services:
  billing:
    build:
      context: ./billing
    ports:
      - "8000:8000"
    volumes:
      - ./billing:/app
    depends_on:
      - db

  gst_backend:
    build:
      context: ./gst_backend
    ports:
      - "8001:8001"
    volumes:
      - ./gst_backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
