services:
  backend:
    build: .
    container_name: gst-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: gst_backend.settings
      DB_NAME: gstdb
      DB_USER: gstuser
      DB_PASSWORD: gstpass
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: False
      ALLOWED_HOSTS: localhost,127.0.0.1
    restart: always

  db:
    image: postgres:15
    container_name: gst-db
    environment:
      POSTGRES_DB: gstdb
      POSTGRES_USER: gstuser
      POSTGRES_PASSWORD: gstpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
